Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
    - .pdf
    - .md
    - .txt
Database:
  DBType: mysql
  Username: root
  Password:
  Host: 127.0.0.1:3306
  DBName: dome7
  TablePrefix: cloud_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: shenlai
  Issuer: CloudDisk
  Expire: 7200
Email:
  Host: smtp.qq.com
  Port: 587
  UserName: 2804991212@qq.com
  Password:
  IsSSL: true
  From: 2804991212@qq.com
  To:
    - 2965502421@qq.com
File:
  DownPath: C:\Users\HUAWEI\Desktop\
  LimitRate: 1000  # KB